# Generated by Django 6.0 on 2025-12-17 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='additional',
            table=None,
        ),
    ]
