# Generated by Django 6.0 on 2025-12-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_additional_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional',
            name='avatar_url',
            field=models.ImageField(blank=True, default=None, upload_to='images/%Y/%m/%d'),
        ),
    ]
